<?php
if (!defined('ABSPATH')) { exit; }

// Owner marker used to detect whether llms.txt belongs to TCT
if (!defined('TCT_LLMS_OWNER_MARK')) {
    define('TCT_LLMS_OWNER_MARK', '<!-- Generated by TCT | owner=tct -->');
}

function tct_llms_physical_path() {
    return trailingslashit(ABSPATH) . 'llms.txt';
}

function tct_llms_owned_by_us() {
    $path = tct_llms_physical_path();
    if (!file_exists($path)) return false;
    $fp = @fopen($path, 'r');
    if (!$fp) return false;
    $buf = '';
    $max = 8192;
    while (!feof($fp) && strlen($buf) < $max) {
        $chunk = fread($fp, 1024);
        if ($chunk === false) break;
        $buf .= $chunk;
    }
    fclose($fp);
    if (!is_string($buf) || $buf === '') return false;
    return (stripos($buf, TCT_LLMS_OWNER_MARK) !== false);
}

function tct_llms_build_content() {
    $endpoint = trim(get_option('tct_endpoint_slug', 'llm'));
    $site_name = get_bloginfo('name');
    $home = home_url('/');
    $sitemap_path = get_option('tct_sitemap_path', '/llm-sitemap.json');
    $terms = function_exists('tct_get_terms_url') ? tct_get_terms_url() : '';
    $pricing = function_exists('tct_get_pricing_url') ? tct_get_pricing_url() : '';

    $include_samples = (int) get_option('tct_llms_include_samples', 1) === 1;
    $include_xml = (int) get_option('tct_llms_include_xml_sitemap', 1) === 1;
    $include_policies = (int) get_option('tct_llms_include_policies', 1) === 1;
    $sample_count = max(1, (int) get_option('tct_llms_sample_count', 20));
    $post_types_raw = get_option('tct_llms_post_types', array('post','page'));
    $post_types = is_array($post_types_raw) ? $post_types_raw : array_map('trim', explode(',', (string)$post_types_raw));

    $lines = array();
    $lines[] = '# ' . $site_name . ' - llms.txt';
    $lines[] = TCT_LLMS_OWNER_MARK;
    $lines[] = '';
    $lines[] = '> Curated discovery file for AI agents. This site exposes AI-optimized JSON endpoints for key content.';
    $lines[] = '';
    $lines[] = '## Important Pages';
    $lines[] = '- ' . $home . ' - Homepage';
    $lines[] = '';

    if ($include_samples) {
        $posts = get_posts(array(
            'post_type' => $post_types,
            'post_status' => 'publish',
            'posts_per_page' => $sample_count,
            'orderby' => 'date',
            'order' => 'DESC',
            'no_found_rows' => true,
            'fields' => 'all',
        ));
        $lines[] = '## LLM JSON Endpoints (samples)';
        foreach ($posts as $p) {
            $title = html_entity_decode(get_the_title($p));
            $url = trailingslashit(get_permalink($p)) . trailingslashit($endpoint);
            $lines[] = '- ' . $url . ' - ' . $title;
        }
        $lines[] = '';
        $lines[] = '_For the full list use the LLM sitemap below._';
        $lines[] = '';
    }

    $lines[] = '## Sitemaps & Feeds';
    $lines[] = '- ' . home_url($sitemap_path) . ' - LLM sitemap (JSON)';
    if ($include_xml) {
        $xmlSitemap = home_url('/sitemap_index.xml');
        $lines[] = '- ' . $xmlSitemap . ' - XML sitemap (if present)';
    }
    $lines[] = '';

    if ($include_policies) {
        $lines[] = '## Policies';
        if (!empty($terms)) {
            $lines[] = '- ' . $terms . ' - Terms / AI Policy';
        }
        if (!empty($pricing)) {
            $lines[] = '- ' . $pricing . ' - Pricing';
        }
        $lines[] = '';
    }

    $lines[] = '_AI agents: prefer `{canonical}/' . $endpoint . '/` per-page JSON and the LLM sitemap for discovery._';

    return implode("\n", $lines) . "\n";
}

function tct_llms_generate_static($overwrite = false) {
    $path = tct_llms_physical_path();
    $exists = file_exists($path);
    $owned = tct_llms_owned_by_us();
    if ($exists && !$owned && !$overwrite) {
        return false;
    }
    if ($exists && !$owned && $overwrite) {
        @copy($path, $path . '.bak-' . gmdate('Ymd-His'));
    }
    $content = tct_llms_build_content();
    // Optional BOM to help some servers identify UTF-8
    $add_bom = true;
    $prefix = $add_bom ? "\xEF\xBB\xBF" : '';
    return (bool) @file_put_contents($path, $prefix . $content);
}

function tct_llms_remove_static() {
    $path = tct_llms_physical_path();
    if (!file_exists($path)) return true;
    if (!tct_llms_owned_by_us()) return false;
    return @unlink($path);
}

// Outputs a human-readable llms.txt at /llms.txt (virtual)
function tct_output_llms_txt() {
    // Optional toggle to disable virtual serving
    $virtual_enabled = (int) get_option('tct_llms_virtual_enabled', 1) === 1;
    if (!$virtual_enabled) {
        status_header(404);
        header('Content-Type: text/plain; charset=utf-8');
        echo 'Not enabled';
        exit;
    }
    $body = tct_llms_build_content();
    status_header(200);
    if (function_exists('nocache_headers')) { nocache_headers(); }
    header('Content-Type: text/plain; charset=utf-8', true);
    header('Cache-Control: private, max-age=0, must-revalidate', true);
    echo $body;
    exit;
}
